# Node.js (TypeScript)
# Build a Node.js (TypeScript) project with yarn.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pr:
  - master
  - releases/*

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      yarn install
      yarn compile
    displayName: "yarn install and compile"

  - task: Bash@3
    inputs:
      targetType: "inline"
      script: "echo -e 'APP_ID=express-mongoose-template\nPORT=3000\nLOG_LEVEL=debug\nREQUEST_LIMIT=100kb\nSESSION_SECRET=mySecret\nOPENAPI_SPEC=/api/v1/spec' > .env"
    displayName: "Generate the `.env` file"

  - script: yarn test:junit
    displayName: "yarn test:junit"

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: "**/test-results.xml"
    displayName: "Publish test results"
