# Node.js (TypeScript)
# Build a Node.js (TypeScript) project with yarn.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pr:
  - master
  - releases/*

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      yarn install
      yarn compile
    displayName: "yarn install and compile"
